#!/usr/bin/env node
// specimen-shelf — assemble an index page over a set of specimen books.
//
//   node cli/specimen-shelf.mjs <config.json> --sites <dir> [-o <file>]
//
// Each book listed in the config must already exist as <dir>/<name>/
// (generated by specimen-site, which writes book.json + banner.svg +
// waxseal.svg alongside the book). Every book gets a faux-Penguin cover
// — tripartite bands in the shelf's series colour, the waxseal standing
// in for the bird — a review pullquote, and its Minard banner plate.
// All release timelines are drawn on ONE shared time scale.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';

const argv = process.argv.slice(2);
if (argv.length === 0) {
  console.error('usage: specimen-shelf <config.json> --sites <dir> [-o file]');
  process.exit(1);
}
const opt = (name, short) => {
  const i = argv.findIndex(a => a === name || (short && a === short));
  return i >= 0 ? argv[i + 1] : undefined;
};
const config = JSON.parse(readFileSync(argv[0], 'utf8'));
const sites = resolve(opt('--sites') ?? '.');
const outFile = resolve(opt('-o') ?? join(sites, 'index.html'));

const books = new Map();
for (const shelf of config.shelves) for (const name of shelf.books) {
  const dir = join(sites, name);
  if (!existsSync(join(dir, 'book.json'))) {
    console.error(`missing book: ${dir} (run specimen-site ${name} first)`);
    process.exit(1);
  }
  books.set(name, {
    meta: JSON.parse(readFileSync(join(dir, 'book.json'), 'utf8')),
    banner: readFileSync(join(dir, 'banner.svg'), 'utf8'),
    seal: readFileSync(join(dir, 'waxseal.svg'), 'utf8'),
  });
}

// one shared time axis across the whole shelf
const allReleases = [...books.values()].flatMap(b => b.meta.releases);
const T0 = Math.min(...allReleases.map(r => r.t));
const T1 = Date.now();

function sparkline(releases) {
  if (!releases.length) return '';
  const W = 260, PAD = 3, AX = 16, H = 26;
  const x = t => (PAD + (W - 2 * PAD) * (t - T0) / (T1 - T0)).toFixed(1);
  const ticks = releases.map(r =>
    `<line x1="${x(r.t)}" y1="${AX - (r.major ? 11 : 7)}" x2="${x(r.t)}" y2="${AX}" stroke="#1a1a1a" stroke-width="${r.major ? 1.5 : 1}"/>`).join('');
  return `<svg viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="release timeline">
    <line x1="${PAD}" y1="${AX}" x2="${W - PAD}" y2="${AX}" stroke="#d8d6cf" stroke-width="1"/>
    ${ticks}
    <circle cx="${W - PAD}" cy="${AX}" r="2.2" fill="none" stroke="#1a1a1a" stroke-width="1"/>
  </svg>`;
}

const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// waxseal reduced to the device alone (no ground, no inscription) — at
// cover scale the circular text is smudge, the ring + pack is the mark
const sealDevice = svg => svg
  .replace('<rect width="100%" height="100%" fill="#fff"/>', '')
  .replace(/<defs>.*?<\/defs>/s, '')
  .replace(/<text[\s\S]*?<\/text>/g, '');

// faux-Penguin cover: colour band / cream / colour band, the cartouche
// up top, title + author on the cream, the seal in the publisher's oval
const cover = (name, color) => {
  const { meta, seal } = books.get(name);
  const t = meta.name;
  const fs = t.length <= 8 ? '1.32rem' : t.length <= 15 ? '1.02rem' : '0.82rem';
  return `
    <div class="cover" style="--band: ${color}">
      <div class="cband ctop"><span class="cartouche">PureScript Books</span></div>
      <div class="cmid">
        <div class="ctitle" style="font-size: ${fs}">${esc(t)}</div>
        <div class="crule"></div>
        <div class="cauthor">${esc(config.authors?.[name] ?? 'PureScript Contributors')}</div>
      </div>
      <div class="cband cbot"><span class="coval">${sealDevice(seal)}</span></div>
    </div>`;
};

const bookCard = (name, color) => {
  const { meta, banner } = books.get(name);
  const q = config.quotes?.[name];
  const stability = meta.releases.length
    ? (meta.releases.length === 1 ? `1 release` : `${meta.releases.length} releases`) +
      (meta.stableSince ? ` &middot; stable since ${meta.stableSince}` : '')
    : '';
  return `
    <div class="book">
      <div class="bookrow">
        <a class="coverlink" href="./${name}/">${cover(name, color)}</a>
        <div class="pull">
          ${q ? `<blockquote>&ldquo;${esc(q.text)}&rdquo;</blockquote>
          <div class="pullsrc">&mdash; <em>${esc(q.source)}</em></div>` : ''}
          <div class="meta">
            <span class="bfacts">v${esc(meta.version)} &middot; ${meta.modules} modules &middot; ${meta.decls} declarations &middot; ${meta.loc} lines</span>
            <span class="bspark">${sparkline(meta.releases)}<span class="bstab">${stability}</span></span>
          </div>
        </div>
      </div>
      <a class="bannerlink" href="./${name}/"><div class="banner">${banner}</div></a>
    </div>`;
};

const shelfSection = shelf => `
  <section class="shelf">
    <h2>${esc(shelf.title)}</h2>
    <p class="blurb">${esc(shelf.blurb)}</p>
    ${shelf.books.map(b => bookCard(b, shelf.color ?? '#1a1a1a')).join('\n')}
  </section>`;

const y0 = new Date(T0).getFullYear();
const page = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(config.title)} &mdash; typeset PureScript</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">
<style>
  :root {
    --paper: #fafaf7; --ink: #1a1a1a; --soft-ink: #555;
    --rule: #d8d6cf; --hairline: #ecebe5; --margin: #8a877e;
    --cream: #f6f0dc;
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--paper); color: var(--ink);
    font-family: Inter, -apple-system, sans-serif; font-weight: 300;
    -webkit-font-smoothing: antialiased; }
  main { max-width: 72rem; margin: 5rem auto 8rem; padding: 0 2.5rem; }
  .kicker { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.22em; color: var(--margin); margin-bottom: 0.6rem; }
  h1 { font-family: Inter, sans-serif; font-size: 4rem; font-weight: 800; letter-spacing: -0.035em; margin: 0 0 0.8rem; }
  .deck { font-size: 1.02rem; color: var(--soft-ink); max-width: 44rem; margin: 0 0 1rem; line-height: 1.65; }
  .scale-note { font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.16em; color: var(--margin); margin: 0 0 4rem; }
  .shelf { margin: 7rem 0; }
  .shelf h2 { font-size: 0.82rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.24em;
    color: var(--soft-ink); border-top: 1px solid var(--ink); padding-top: 0.7rem; margin: 0 0 0.6rem; }
  .blurb { font-size: 0.92rem; color: var(--soft-ink); max-width: 42rem; line-height: 1.65; margin: 0 0 3.5rem; }
  .book { margin: 0 0 6.5rem; }
  .bookrow { display: flex; gap: 3rem; align-items: stretch; margin-bottom: 1.6rem; }

  /* ---- the cover ---- */
  .coverlink { text-decoration: none; color: inherit; flex: 0 0 auto; }
  .cover { width: 215px; aspect-ratio: 0.63; display: flex; flex-direction: column;
    box-shadow: 2px 3px 0 rgba(26,26,26,0.14); transition: box-shadow .2s ease, transform .2s ease; }
  .coverlink:hover .cover { box-shadow: 3px 5px 0 rgba(26,26,26,0.2); transform: translateY(-2px); }
  .cband { background: var(--band); display: flex; align-items: center; justify-content: center; }
  .ctop { flex: 0 0 21%; }
  .cbot { flex: 1 1 auto; }
  .cmid { flex: 0 0 46%; background: var(--cream); display: flex; flex-direction: column;
    align-items: center; justify-content: center; gap: 0.55rem; padding: 0 0.8rem; text-align: center; }
  .cartouche { background: var(--cream); color: var(--band); font-size: 0.58rem; font-weight: 600;
    text-transform: uppercase; letter-spacing: 0.18em; padding: 0.28rem 0.9rem; border-radius: 999px; }
  .ctitle { font-family: 'JetBrains Mono', monospace; font-weight: 700; letter-spacing: 0.01em; overflow-wrap: anywhere; }
  .crule { width: 3.2rem; border-top: 1px solid var(--ink); }
  .cauthor { font-size: 0.62rem; text-transform: uppercase; letter-spacing: 0.16em; color: var(--soft-ink); }
  .coval { background: var(--cream); border-radius: 50%; width: 72px; height: 72px;
    display: flex; align-items: center; justify-content: center; }
  .coval svg { width: 60px; height: 60px; }

  /* ---- the pullquote ---- */
  .pull { display: flex; flex-direction: column; justify-content: center; min-width: 0; flex: 1 1 auto; }
  .pull blockquote { margin: 0; font-family: Georgia, 'Times New Roman', serif; font-style: italic;
    font-size: 1.65rem; line-height: 1.35; color: var(--ink); font-weight: 400; max-width: 34rem; }
  .pullsrc { margin-top: 0.8rem; font-size: 0.78rem; letter-spacing: 0.06em; color: var(--margin); }
  .pullsrc em { font-style: italic; }
  .meta { margin-top: 2.2rem; display: flex; align-items: center; gap: 1.6rem; flex-wrap: wrap; }
  .bfacts { font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.14em; color: var(--margin); }
  .bspark { display: flex; align-items: center; gap: 0.8rem; }
  .bspark svg { display: block; }
  .bstab { font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.14em; color: var(--margin); }

  /* ---- the banner plate ---- */
  .bannerlink { display: block; text-decoration: none; }
  .banner { border: 1px solid var(--hairline); background: #fff; transition: border-color .2s ease; }
  .bannerlink:hover .banner { border-color: var(--ink); }
  .banner svg { display: block; width: 100%; height: auto; }

  .footnote { margin-top: 6rem; padding-top: 1rem; border-top: 1px solid var(--hairline);
    font-size: 0.8rem; color: var(--margin); max-width: 44rem; line-height: 1.65; }
  .colophon { margin-top: 2.5rem; font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.18em; color: var(--margin); }
  @media (max-width: 860px) {
    .bookrow { flex-direction: column; }
    .pull blockquote { font-size: 1.3rem; }
  }
</style>
</head>
<body>
<main>
  <div class="kicker">${esc(config.kicker)}</div>
  <h1>${esc(config.title)}</h1>
  <p class="deck">${esc(config.deck)}</p>
  <p class="scale-note">All release timelines drawn to one scale &middot; ${y0} &ndash; today</p>
  ${config.shelves.map(shelfSection).join('\n')}
  <p class="footnote">${esc(config.footnote)}</p>
  <p class="colophon">Typeset by <a href="https://github.com/afcondon/specimen" style="color:inherit">specimen</a> &middot; ${new Date().toISOString().slice(0, 10)}</p>
</main>
</body>
</html>
`;

writeFileSync(outFile, page);
console.log(`${books.size} books on ${config.shelves.length} shelves → ${outFile}`);
