#!/usr/bin/env node
// specimen-shelf — assemble an index page over a set of specimen books.
//
//   node cli/specimen-shelf.mjs <config.json> --sites <dir> [-o <file>]
//
// Each book listed in the config must already exist as <dir>/<name>/
// (generated by specimen-site, which writes book.json + banner.svg
// alongside the book). The shelf page inlines every banner and draws
// all release timelines on ONE shared time scale, so stability reads
// across the whole shelf at a glance.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';

const argv = process.argv.slice(2);
if (argv.length === 0) {
  console.error('usage: specimen-shelf <config.json> --sites <dir> [-o file]');
  process.exit(1);
}
const opt = (name, short) => {
  const i = argv.findIndex(a => a === name || (short && a === short));
  return i >= 0 ? argv[i + 1] : undefined;
};
const config = JSON.parse(readFileSync(argv[0], 'utf8'));
const sites = resolve(opt('--sites') ?? '.');
const outFile = resolve(opt('-o') ?? join(sites, 'index.html'));

const books = new Map();
for (const shelf of config.shelves) for (const name of shelf.books) {
  const dir = join(sites, name);
  if (!existsSync(join(dir, 'book.json'))) {
    console.error(`missing book: ${dir} (run specimen-site ${name} first)`);
    process.exit(1);
  }
  books.set(name, {
    meta: JSON.parse(readFileSync(join(dir, 'book.json'), 'utf8')),
    banner: readFileSync(join(dir, 'banner.svg'), 'utf8'),
  });
}

// one shared time axis across the whole shelf
const allReleases = [...books.values()].flatMap(b => b.meta.releases);
const T0 = Math.min(...allReleases.map(r => r.t));
const T1 = Date.now();

function sparkline(releases) {
  if (!releases.length) return '';
  const W = 260, PAD = 3, AX = 16, H = 26;
  const x = t => (PAD + (W - 2 * PAD) * (t - T0) / (T1 - T0)).toFixed(1);
  const ticks = releases.map(r =>
    `<line x1="${x(r.t)}" y1="${AX - (r.major ? 11 : 7)}" x2="${x(r.t)}" y2="${AX}" stroke="#1a1a1a" stroke-width="${r.major ? 1.5 : 1}"/>`).join('');
  return `<svg viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="release timeline">
    <line x1="${PAD}" y1="${AX}" x2="${W - PAD}" y2="${AX}" stroke="#d8d6cf" stroke-width="1"/>
    ${ticks}
    <circle cx="${W - PAD}" cy="${AX}" r="2.2" fill="none" stroke="#1a1a1a" stroke-width="1"/>
  </svg>`;
}

const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const bookCard = name => {
  const { meta, banner } = books.get(name);
  const stability = meta.releases.length
    ? (meta.releases.length === 1
        ? `1 release`
        : `${meta.releases.length} releases`) +
      (meta.stableSince ? ` &middot; stable since ${meta.stableSince}` : '')
    : '';
  return `
    <a class="book" href="./${name}/">
      <div class="banner">${banner}</div>
      <div class="meta">
        <span class="bname">${esc(meta.name)}</span>
        <span class="bfacts">v${esc(meta.version)} &middot; ${meta.modules} modules &middot; ${meta.decls} declarations &middot; ${meta.loc} lines</span>
        <span class="bspark">${sparkline(meta.releases)}<span class="bstab">${stability}</span></span>
      </div>
    </a>`;
};

const shelfSection = shelf => `
  <section class="shelf">
    <h2>${esc(shelf.title)}</h2>
    <p class="blurb">${esc(shelf.blurb)}</p>
    ${shelf.books.map(bookCard).join('\n')}
  </section>`;

const y0 = new Date(T0).getFullYear();
const page = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(config.title)} &mdash; typeset PureScript</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">
<style>
  :root {
    --paper: #fafaf7; --ink: #1a1a1a; --soft-ink: #555;
    --rule: #d8d6cf; --hairline: #ecebe5; --margin: #8a877e;
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--paper); color: var(--ink);
    font-family: Inter, -apple-system, sans-serif; font-weight: 300;
    -webkit-font-smoothing: antialiased; }
  main { max-width: 72rem; margin: 4rem auto 6rem; padding: 0 2rem; }
  .kicker { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.22em; color: var(--margin); margin-bottom: 0.6rem; }
  h1 { font-family: 'JetBrains Mono', monospace; font-size: 4rem; font-weight: 700; letter-spacing: -0.02em; margin: 0 0 0.8rem; }
  .deck { font-size: 1.02rem; color: var(--soft-ink); max-width: 44rem; margin: 0 0 1rem; line-height: 1.6; }
  .scale-note { font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.16em; color: var(--margin); margin: 0 0 3rem; }
  .shelf { margin: 4.5rem 0; }
  .shelf h2 { font-size: 0.82rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.24em;
    color: var(--soft-ink); border-top: 1px solid var(--ink); padding-top: 0.7rem; margin: 0 0 0.6rem; }
  .blurb { font-size: 0.92rem; color: var(--soft-ink); max-width: 42rem; line-height: 1.6; margin: 0 0 2.2rem; }
  .book { display: block; text-decoration: none; color: inherit; margin: 0 0 3.4rem; }
  .book .banner { border: 1px solid var(--hairline); background: #fff; transition: border-color .2s ease; }
  .book:hover .banner { border-color: var(--ink); }
  .book .banner svg { display: block; width: 100%; height: auto; }
  .book .meta { display: flex; align-items: baseline; gap: 1.6rem; padding-top: 0.55rem; flex-wrap: wrap; }
  .bname { font-family: 'JetBrains Mono', monospace; font-weight: 700; font-size: 1.05rem; }
  .bfacts { font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.14em; color: var(--margin); }
  .bspark { margin-left: auto; display: flex; align-items: center; gap: 0.8rem; }
  .bspark svg { display: block; }
  .bstab { font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.14em; color: var(--margin); }
  .footnote { margin-top: 5rem; padding-top: 1rem; border-top: 1px solid var(--hairline);
    font-size: 0.8rem; color: var(--margin); max-width: 44rem; line-height: 1.65; }
  .colophon { margin-top: 2.5rem; font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.18em; color: var(--margin); }
</style>
</head>
<body>
<main>
  <div class="kicker">${esc(config.kicker)}</div>
  <h1>${esc(config.title)}</h1>
  <p class="deck">${esc(config.deck)}</p>
  <p class="scale-note">All release timelines drawn to one scale &middot; ${y0} &ndash; today</p>
  ${config.shelves.map(shelfSection).join('\n')}
  <p class="footnote">${esc(config.footnote)}</p>
  <p class="colophon">Typeset by <a href="https://github.com/afcondon/specimen" style="color:inherit">specimen</a> &middot; ${new Date().toISOString().slice(0, 10)}</p>
</main>
</body>
</html>
`;

writeFileSync(outFile, page);
console.log(`${books.size} books on ${config.shelves.length} shelves → ${outFile}`);
