-- | The seam between the Halogen island and the server-rendered page.
-- |
-- | The shelf index is a static document: nineteen books' worth of
-- | inlined banners and seals, generated by `specimen-shelf`. Halogen
-- | owns only the tab bar. Everything it needs to know about the page
-- | arrives through this module, and the only thing it does to the page
-- | is hide the shelves that aren't showing.
-- |
-- | Both directions are FFI on purpose. The payload is emitted by the
-- | generator two files away with a shape fixed here, so a decoder
-- | would be ceremony around a contract that is already checked by the
-- | only two things that can break it. And the sections being toggled
-- | are not Halogen's to render — reaching for them by attribute is the
-- | honest expression of that, rather than pretending the vdom owns
-- | markup it never produced.
module Specimen.Shelf.Page
  ( Shelf
  , readShelves
  , showOnly
  ) where

import Prelude

import Effect (Effect)

-- | One shelf, as written into the page's `#shelf-index` payload.
-- | `color` is the shelf's band colour, which the tab wears.
type Shelf =
  { key :: String
  , label :: String
  , color :: String
  }

-- | Read the shelf list the generator embedded. An empty array means
-- | the payload is missing or malformed, in which case the caller
-- | should leave the page exactly as the server rendered it.
foreign import readShelves :: Effect (Array Shelf)

-- | Hide every shelf section but one.
foreign import showOnly :: String -> Effect Unit
